namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0
readme: README.md

authors:
  - Ruslan Mamedov

description: Custom Ansible collection with module and role for file creation

license:
  - GPL-3.0-or-later

min_ansible_version: "2.13"

tags:
  - ansible
  - module
  - role
  - homework
